### ISSUE TITLE
Applying CSS efficiently

### ISSUE THREAD

**Issue by jim-rosales** [AwesomeAartvark/prj-rev-bwfs-dasmoto#3]
Marvelous job ensuring there are no duplicate styles in your stylesheet! You did a fantastic job applying the styles all the h2s shared to the general element and then using their ids to apply the unique color they all have. 

https://github.com/AwesomeAartvark/prj-rev-bwfs-dasmoto/blob/34a7e3bb49e26733ec6c4d20800642d84a36142c/DasmotosArts%26Crafts/css/stylesheet.css#L16-L35

**Comment by AwesomeAartvark** [comment]
I'm glad using ids on the h2 elements was a correct way to apply the colors! Throughout the lessons, we seemed to be applying ids mainly to divs when adjusting css styles, so I wasn't sure if it would be better to add a div around the h2 elements or not. But it seemed redundant since we were only changing the h2 styles, so I'm glad this is a viable option as well!
